# Generated by Django 4.2.29 on 2026-04-16 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_push_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('event_reminder', 'event_reminder'), ('new_event', 'new_event'), ('event_update', 'event_update'), ('community_post', 'community_post'), ('comment_reply', 'comment_reply'), ('new_member', 'new_member'), ('event_full', 'event_full'), ('admin_broadcast', 'admin_broadcast')], max_length=50),
        ),
    ]
