# Generated by Django 4.2.29 on 2026-04-16 03:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0003_admin_broadcast_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlastNotificationAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('target_mode', models.CharField(choices=[('user_ids', 'user_ids'), ('all_users', 'all_users'), ('interests', 'interests')], max_length=30)),
                ('target_count', models.PositiveIntegerField(default=0)),
                ('queued_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('payload_summary', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blast_notification_audits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'blast_notification_audits',
            },
        ),
    ]
