# Generated by Django 4.2.29 on 2026-04-16 04:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatTurn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(blank=True, default='', max_length=64)),
                ('intent', models.CharField(max_length=32)),
                ('prompt_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('prompt_length', models.PositiveIntegerField(default=0)),
                ('llm_used', models.BooleanField(default=False)),
                ('card_event_count', models.PositiveSmallIntegerField(default=0)),
                ('card_community_count', models.PositiveSmallIntegerField(default=0)),
                ('card_area_count', models.PositiveSmallIntegerField(default=0)),
                ('helpful', models.BooleanField(blank=True, null=True)),
                ('feedback_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_turns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_turns',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='chat_turns_user_id_bfd4d8_idx')],
            },
        ),
    ]
