# Generated by Django 4.2.29 on 2026-04-16 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatAnswerCorrection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('normalized_query', models.CharField(max_length=500, unique=True)),
                ('corrected_reply', models.TextField()),
                ('intent', models.CharField(blank=True, default='', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'chat_answer_corrections',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='chatturn',
            name='assistant_reply',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='chatturn',
            name='cards_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='chatturn',
            name='correction_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatturn',
            name='sources_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='chatturn',
            name='user_message_redacted',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddIndex(
            model_name='chatturn',
            index=models.Index(fields=['intent', '-created_at'], name='chat_turns_intent_744e8d_idx'),
        ),
        migrations.AddField(
            model_name='chatanswercorrection',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_corrections_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatanswercorrection',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_corrections_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='chatanswercorrection',
            index=models.Index(fields=['is_active', '-updated_at'], name='chat_answer_is_acti_d0b95b_idx'),
        ),
        migrations.AddIndex(
            model_name='chatanswercorrection',
            index=models.Index(fields=['intent', '-updated_at'], name='chat_answer_intent_e41605_idx'),
        ),
    ]
