# Generated by Django 4.2.29 on 2026-04-16 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatanswercorrection_chatturn_assistant_reply_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatanswercorrection',
            name='source_ref',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='chatanswercorrection',
            name='source_type',
            field=models.CharField(default='manual', max_length=16),
        ),
    ]
