# Generated by Django 4.2.29 on 2026-04-16 02:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0007_event_has_registration_deadline'),
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationSignal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('signal_type', models.CharField(choices=[('view', 'view'), ('like', 'like'), ('join', 'join'), ('save', 'save'), ('share', 'share'), ('dislike', 'dislike')], max_length=30)),
                ('value', models.DecimalField(decimal_places=2, default=1, max_digits=7)),
                ('dwell_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('platform', models.CharField(blank=True, choices=[('android', 'android'), ('ios', 'ios'), ('web', 'web')], max_length=20, null=True)),
                ('source', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_signals', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_signals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recommendation_signals',
                'indexes': [models.Index(fields=['user', 'created_at'], name='recommendat_user_id_f3fb26_idx'), models.Index(fields=['event', 'created_at'], name='recommendat_event_i_fb5303_idx'), models.Index(fields=['user', 'event'], name='recommendat_user_id_3e6ca8_idx'), models.Index(fields=['signal_type', 'created_at'], name='recommendat_signal__d1fd21_idx')],
            },
        ),
    ]
