# Generated by Django 4.2.29 on 2026-04-01 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('preferred_days', models.JSONField(blank=True, null=True)),
                ('preferred_time', models.CharField(blank=True, choices=[('morning', 'morning'), ('afternoon', 'afternoon'), ('evening', 'evening'), ('night', 'night')], max_length=20, null=True)),
                ('preferred_location', models.CharField(blank=True, max_length=100, null=True)),
                ('notification_enabled', models.BooleanField(default=True)),
                ('email_notification', models.BooleanField(default=True)),
                ('push_notification', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences_row', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_preferences',
            },
        ),
        migrations.CreateModel(
            name='ActivityHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('joined_event', 'joined_event'), ('created_event', 'created_event'), ('joined_community', 'joined_community'), ('created_community', 'created_community'), ('posted_thread', 'posted_thread'), ('commented', 'commented')], max_length=50)),
                ('description', models.TextField()),
                ('related_type', models.CharField(blank=True, max_length=50, null=True)),
                ('related_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'activity histories',
                'db_table': 'activity_history',
            },
        ),
        migrations.CreateModel(
            name='UserInterest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interest_name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interest_rows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_interests',
                'unique_together': {('user', 'interest_name')},
            },
        ),
    ]
