# Generated by Django 4.2.29 on 2026-04-15 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_activityhistory_activity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityhistory',
            name='activity_type',
            field=models.CharField(choices=[('joined_event', 'joined_event'), ('attended_event', 'attended_event'), ('created_event', 'created_event'), ('joined_community', 'joined_community'), ('left_community', 'left_community'), ('created_community', 'created_community'), ('posted_thread', 'posted_thread'), ('commented', 'commented')], max_length=50),
        ),
    ]
