"""
Django settings for ngumpulyuk_project project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import environ
from pathlib import Path
from datetime import timedelta

env = environ.Env(
    DEBUG=(bool, False),
    DJANGO_ENV=(str, 'development'),
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

environ.Env.read_env(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

DJANGO_ENV = env('DJANGO_ENV')  # 'development' atau 'production'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['localhost', '127.0.0.1', 'testserver'])

FRONTEND_URL = env('FRONTEND_URL')

CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOW_CREDENTIALS = True

CORS_ALLOWED_ORIGINS = [
    FRONTEND_URL,
]

CSRF_TRUSTED_ORIGINS = [
    FRONTEND_URL,
]

CORS_ALLOW_HEADERS = [
    'authorization',
    'content-type',
]

# Application definition

INSTALLED_APPS = [
    'ngumpulyuk_app.authentication.apps.AuthenticationConfig',
    'ngumpulyuk_app.common.apps.CommonConfig',
    'ngumpulyuk_app.users.apps.UsersConfig',
    'ngumpulyuk_app.events.apps.EventsConfig',
    'ngumpulyuk_app.communities.apps.CommunitiesConfig',
    'ngumpulyuk_app.discussions.apps.DiscussionsConfig',
    'ngumpulyuk_app.notifications.apps.NotificationsConfig',
    'ngumpulyuk_app.recommendations.apps.RecommendationsConfig',
    'ngumpulyuk_app.chat.apps.ChatConfig',
    'ngumpulyuk_app.social_accounts.apps.SocialAccountsConfig',
    'rest_framework',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'drf_spectacular',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ngumpulyuk_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ngumpulyuk_project.wsgi.application'


# Database

DATABASES = {}
if DJANGO_ENV == 'production' or env('DATABASE_URL', default=None):
    DATABASES['default'] = env.db('DATABASE_URL')
else:
    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }

AUTH_USER_MODEL="authentication.User"

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_THROTTLE_CLASSES': (
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ),
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/minute',
        'user': '500/minute',
        'blast_notifications': '10/hour',
        'chat': '45/minute',
        'chat_feedback': '120/minute',
    },
    'EXCEPTION_HANDLER': 'ngumpulyuk_app.common.exceptions.custom_exception_handler',
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'NgumpulYuk API',
    'DESCRIPTION': 'REST API untuk platform NgumpulYuk (events, communities, threads, notifications). '
    'Gunakan **Authorize** dan skema Bearer: `Bearer <access_token>`.',
    'VERSION': '1.0.0',
    'SCHEMA_PATH_PREFIX': '/api/v1',
    'SERVE_INCLUDE_SCHEMA': False,
    'POSTPROCESSING_HOOKS': [
        'ngumpulyuk_app.common.spectacular_hooks.use_bearer_auth_only',
    ],
    'COMPONENT_SPLIT_REQUEST': True,
    'SWAGGER_UI_SETTINGS': {
        'persistAuthorization': True,
        'displayRequestDuration': True,
    },
    'APPEND_COMPONENTS': {
        'securitySchemes': {
            'BearerAuth': {
                'type': 'http',
                'scheme': 'bearer',
                'bearerFormat': 'JWT',
                'description': 'JWT access token dari POST /auth/login/ atau /auth/register/ (path relatif setelah prefix /api/v1).',
            }
        }
    },
    'TAGS': [
        {'name': 'Authentication', 'description': 'Register, login, refresh & logout JWT'},
        {'name': 'Users', 'description': 'Profil pengguna, onboarding, riwayat aktivitas'},
        {'name': 'Events', 'description': 'Event, peserta, join/leave'},
        {'name': 'Communities', 'description': 'Komunitas, anggota, thread di dalam komunitas'},
        {'name': 'Discussions', 'description': 'Thread, komentar, suka'},
        {'name': 'Notifications', 'description': 'Notifikasi pengguna'},
        {'name': 'Notifications (Admin)', 'description': 'Blast notifikasi'},
        {'name': 'Recommendations', 'description': 'Rekomendasi event (AI/heuristik)'},
        {'name': 'Chat', 'description': 'Asisten chat (FAQ + retrieval; LLM opsional)'},
    ],
}

# Chat assistant — Gemini (Google AI Studio) opsional; tanpa key = mode rule + retrieval saja
CHAT_LLM_ENABLED = env.bool('CHAT_LLM_ENABLED', default=False)
CHAT_GEMINI_API_KEY = env('CHAT_GEMINI_API_KEY', default=None)
CHAT_GEMINI_MODEL = env('CHAT_GEMINI_MODEL', default='gemini-2.0-flash')

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=5),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    "AUTH_HEADER_TYPES": ("Bearer",),
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email
if DJANGO_ENV == 'production':
    EMAIL_HOST = 'smtp.gmail.com'
    EMAIL_PORT = 587
    EMAIL_USE_TLS = True
    EMAIL_HOST_USER = env('EMAIL_HOST_USER')      # Alamat Gmail Anda, misal: info@ngumpulyuk.id
    EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD')  # Gmail App Password (16 karakter)
else:
    EMAIL_HOST = 'sandbox.smtp.mailtrap.io'
    EMAIL_PORT = 2525
    EMAIL_USE_TLS = True
    EMAIL_HOST_USER = env('EMAIL_HOST_USER')
    EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD')

EMAIL_TIMEOUT = 10
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL', default='info@ngumpulyuk.id')
EMAIL_FROM_NAME = env('EMAIL_FROM_NAME', default='NgumpulYuk')
SERVER_EMAIL = DEFAULT_FROM_EMAIL

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {'class': 'logging.StreamHandler'},
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'ngumpulyuk_app.authentication': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

GOOGLE_CLIENT_ID=env('GOOGLE_CLIENT_ID')
GOOGLE_CLIENT_SECRET=env('GOOGLE_CLIENT_SECRET')
SOCIAL_AUTH_PASSWORD=env('SOCIAL_AUTH_PASSWORD')

# Firebase Cloud Messaging
FIREBASE_CREDENTIALS_PATH = env('FIREBASE_CREDENTIALS_PATH', default=None)